// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FundUIClient is the client API for FundUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundUIClient interface {
	// ListEngineSpecs returns a list of Fund Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FundUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type fundUIClient struct {
	cc grpc.ClientConnInterface
}

func NewFundUIClient(cc grpc.ClientConnInterface) FundUIClient {
	return &fundUIClient{cc}
}

func (c *fundUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FundUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &FundUI_ServiceDesc.Streams[0], "/v1.FundUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &fundUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FundUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type fundUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *fundUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fundUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.FundUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundUIServer is the server API for FundUI service.
// All implementations must embed UnimplementedFundUIServer
// for forward compatibility
type FundUIServer interface {
	// ListEngineSpecs returns a list of Fund Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, FundUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedFundUIServer()
}

// UnimplementedFundUIServer must be embedded to have forward compatible implementations.
type UnimplementedFundUIServer struct {
}

func (UnimplementedFundUIServer) ListEngineSpecs(*ListEngineSpecsRequest, FundUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedFundUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedFundUIServer) mustEmbedUnimplementedFundUIServer() {}

// UnsafeFundUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundUIServer will
// result in compilation errors.
type UnsafeFundUIServer interface {
	mustEmbedUnimplementedFundUIServer()
}

func RegisterFundUIServer(s grpc.ServiceRegistrar, srv FundUIServer) {
	s.RegisterService(&FundUI_ServiceDesc, srv)
}

func _FundUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FundUIServer).ListEngineSpecs(m, &fundUIListEngineSpecsServer{stream})
}

type FundUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type fundUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *fundUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FundUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FundUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundUI_ServiceDesc is the grpc.ServiceDesc for FundUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FundUI",
	HandlerType: (*FundUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _FundUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _FundUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fund-ui.proto",
}
